### ISSUE TITLE
Introduce fail-on-issues option

### ISSUE THREAD

**Issue by macbre** [macbre/actions-index-digest#9]
```yaml
    - name: Install and run index-digest
      id: run-index-digest
      uses: macbre/actions-index-digest@0.7.0
      with:
        index-digest-version: "1.5.0"  # or "latest" if you wish use the master version
        index-digest-dsn: "mysql://test_user:test_password@127.0.0.1:3306/test_db"
        index-digest-report-file: "./report.yml"
        fail-on-issues: true
```

This option will then trigger the following check:

https://github.com/macbre/actions-index-digest#asserting-using-number-of-issues-reported

```yaml
    - name: Verify index-digest results
      if: steps.run-index-digest.outputs.number-of-issues >= 0
      run: |
        echo "::warning::index-digest issues reported: ${{ steps.run-index-digest.outputs.number-of-issues }}"
        echo "::group::index-digest report"
        cat ./report.yml
        echo "::endgroup::"

        echo "::error::index-digest database performance check failed"
        exit 1
```
